# Generated by orbitfabric-openc3-cosmos-adapter
# Target-owned artifact; not a generic OrbitFabric Core contract.
# Scenario: payload_stop_acquisition_verification
# Scenario SHA256: b19ff6e1cf3c45cdb81e239d30aad97e8b6f037703c06f27102b762e69a1146a
# Core Input Set SHA256: 4bbdca769e4b8fdee51719a47acaa49e9a552b4360f96d8664947514b074ef34
# Projection Profile: engineering-story-flight-ground-cosmos@0.1.0
# Projection Profile SHA256: 3ac68f9bace16775812a9b3bbe17650c9e26a9e09e4d50b49f99b31322c08b41
# COSMOS baseline: v7.3.0

from openc3.script import *

# op-0001 <- atom-0004 (cmd.stop_acquisition)
cmd('FPRIME Ref.payload.OF_StopAcquisition')

# op-0002 <- atom-0006 (tm.acquisition_active)
wait_check('FPRIME Ref.payload.OF_AcquisitionActive OF_AcquisitionActive == 0', 5, type='RAW')
