export interface RelationshipPresentation {
  forwardLabel: string;
  inverseLabel: string;
  group: "structure" | "operations" | "fdir" | "data" | "other";
}

const PRESENTATIONS: Record<string, RelationshipPresentation> = {
  autonomous_action_dispatches_command: {
    forwardLabel: "dispatches",
    inverseLabel: "dispatched by autonomous action",
    group: "operations",
  },
  autonomous_action_triggered_by_fault: {
    forwardLabel: "triggered by",
    inverseLabel: "triggers autonomous action",
    group: "fdir",
  },
  autonomous_action_uses_command_source: {
    forwardLabel: "uses command source",
    inverseLabel: "used by autonomous action",
    group: "operations",
  },
  commandability_rule_constrains_command: {
    forwardLabel: "constrains",
    inverseLabel: "constrained by",
    group: "operations",
  },
  command_emits_event: {
    forwardLabel: "emits",
    inverseLabel: "emitted by command",
    group: "operations",
  },
  command_targets_subsystem: {
    forwardLabel: "targets",
    inverseLabel: "targeted by command",
    group: "structure",
  },
  data_product_produced_by_payload: {
    forwardLabel: "produced by",
    inverseLabel: "produces data product",
    group: "data",
  },
  data_product_produced_by_subsystem: {
    forwardLabel: "produced by",
    inverseLabel: "produces data product",
    group: "data",
  },
  downlink_flow_includes_data_product: {
    forwardLabel: "includes eligible product",
    inverseLabel: "eligible in downlink flow",
    group: "data",
  },
  event_sourced_from_subsystem: {
    forwardLabel: "sourced from",
    inverseLabel: "sources event",
    group: "structure",
  },
  fault_emits_event: {
    forwardLabel: "emits",
    inverseLabel: "emitted by fault",
    group: "fdir",
  },
  fault_observes_telemetry: {
    forwardLabel: "observes",
    inverseLabel: "observed by fault",
    group: "fdir",
  },
  fault_recovery_dispatches_command: {
    forwardLabel: "recovery dispatches",
    inverseLabel: "dispatched by fault recovery",
    group: "fdir",
  },
  fault_recovery_targets_mode: {
    forwardLabel: "recovery targets",
    inverseLabel: "targeted by fault recovery",
    group: "fdir",
  },
  fault_sourced_from_subsystem: {
    forwardLabel: "sourced from",
    inverseLabel: "sources fault",
    group: "structure",
  },
  packet_includes_telemetry: {
    forwardLabel: "includes",
    inverseLabel: "included in packet",
    group: "data",
  },
  payload_accepts_command: {
    forwardLabel: "accepts",
    inverseLabel: "accepted by payload",
    group: "operations",
  },
  payload_belongs_to_subsystem: {
    forwardLabel: "belongs to",
    inverseLabel: "has payload contract",
    group: "structure",
  },
  payload_generates_event: {
    forwardLabel: "generates",
    inverseLabel: "generated by payload",
    group: "operations",
  },
  payload_may_raise_fault: {
    forwardLabel: "may raise",
    inverseLabel: "may be raised by payload",
    group: "fdir",
  },
  payload_produces_telemetry: {
    forwardLabel: "produces",
    inverseLabel: "produced by payload",
    group: "data",
  },
  recovery_intent_includes_command: {
    forwardLabel: "includes command",
    inverseLabel: "included in recovery intent",
    group: "fdir",
  },
  recovery_intent_reacts_to_event: {
    forwardLabel: "reacts to",
    inverseLabel: "has recovery intent",
    group: "fdir",
  },
  recovery_intent_reacts_to_fault: {
    forwardLabel: "reacts to",
    inverseLabel: "has recovery intent",
    group: "fdir",
  },
  recovery_intent_targets_mode: {
    forwardLabel: "targets mode",
    inverseLabel: "targeted by recovery intent",
    group: "fdir",
  },
  telemetry_sourced_from_subsystem: {
    forwardLabel: "sourced from",
    inverseLabel: "sources telemetry",
    group: "structure",
  },
};

export function relationshipPresentation(
  relationshipType: string,
): RelationshipPresentation | null {
  return PRESENTATIONS[relationshipType] ?? null;
}
